name: open_local_ui
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
repository: "github.com/WilliamKarolDiCioccio/open_local_ui"

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Basic Flutter Packages
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter

  # Utility Packages
  uuid: ^4.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  units_converter: ^3.0.0
  path: ^1.9.0
  archive: ^3.6.1
  http: ^1.2.1
  gap: ^3.0.1
  indexed: ^0.0.8
  awesome_snackbar_content: ^0.1.3
  intl: any

  # Theming and UI
  adaptive_theme: ^3.6.0
  system_theme: ^2.3.1
  flex_color_picker: ^3.5.0

  # Icons and Graphics
  unicons: ^2.1.1
  image: ^4.2.0
  flutter_image_converter: ^0.3.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1

  # Splash Screen
  flutter_native_splash: ^2.4.0

  # Window Management
  bitsdojo_window: ^0.1.6
  windows_taskbar: ^1.1.2

  # Local Storage
  hive_flutter: ^1.1.0
  isar_flutter_libs: ^3.1.0+1

  # JSON and Annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.0.1

  # File Picker
  file_picker: ^8.0.2

  # Audio and Video
  audioplayers: ^6.0.0

  # Markdown and HTML
  markdown_widget: ^2.3.2+6
  markdown: ^7.2.2
  html: ^0.15.4

  # Feedback and User Interaction
  feedback: ^3.1.0
  super_drag_and_drop: ^0.8.12

  # Logging
  logger: ^2.2.0

  # URL Launcher
  url_launcher: ^6.2.6

  # Supabase Integration
  supabase_flutter: ^2.5.2

  # Device and Package Info
  package_info_plus: ^8.0.0
  language_code: ^0.5.3+2
  system_info2: ^4.0.0
  gpu_info: ^0.0.3

  # Environment Variables
  envied: ^0.5.4+1

  # Animations
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.1

  # GRPC and Protocol Buffers
  grpc: ^3.2.4
  protoc_plugin: ^21.1.2
  protobuf: ^3.1.0

  # LangChain Integration
  langchain: ^0.7.3
  langchain_ollama: ^0.2.2+1
  introduction_screen: ^3.1.14
  rive: ^0.13.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1
  envied_generator: ^0.5.4+1
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  assets:
    # Prompts
    - assets/prompts/default.txt
    - assets/prompts/sessions_title_generator.txt
    # Model Metadata
    - assets/metadata/ollama_models.json
    # Logos
    - assets/graphics/logos/flutter.svg
    - assets/graphics/logos/langchain.svg
    - assets/graphics/logos/supabase.svg
    - assets/graphics/logos/ollama.svg
    - assets/graphics/logos/apache.svg
    - assets/graphics/logos/arduino.svg
    - assets/graphics/logos/bash.svg
    - assets/graphics/logos/c.svg
    - assets/graphics/logos/clojure.svg
    - assets/graphics/logos/cmake.svg
    - assets/graphics/logos/cpp.svg
    - assets/graphics/logos/crystal.svg
    - assets/graphics/logos/cs.svg
    - assets/graphics/logos/css.svg
    - assets/graphics/logos/dart.svg
    - assets/graphics/logos/delphi.svg
    - assets/graphics/logos/dockerfile.svg
    - assets/graphics/logos/elixir.svg
    - assets/graphics/logos/erlang.svg
    - assets/graphics/logos/flutter.svg
    - assets/graphics/logos/fortran.svg
    - assets/graphics/logos/glsl.svg
    - assets/graphics/logos/go.svg
    - assets/graphics/logos/gradle.svg
    - assets/graphics/logos/haskell.svg
    - assets/graphics/logos/java.svg
    - assets/graphics/logos/javascript.svg
    - assets/graphics/logos/json.svg
    - assets/graphics/logos/julia.svg
    - assets/graphics/logos/kotlin.svg
    - assets/graphics/logos/langchain.svg
    - assets/graphics/logos/less.svg
    - assets/graphics/logos/llvm.svg
    - assets/graphics/logos/lua.svg
    - assets/graphics/logos/makefile.svg
    - assets/graphics/logos/nginx.svg
    - assets/graphics/logos/nsis.svg
    - assets/graphics/logos/ocaml.svg
    - assets/graphics/logos/ollama.svg
    - assets/graphics/logos/perl.svg
    - assets/graphics/logos/php.svg
    - assets/graphics/logos/powershell.svg
    - assets/graphics/logos/python.svg
    - assets/graphics/logos/ruby.svg
    - assets/graphics/logos/rust.svg
    - assets/graphics/logos/scala.svg
    - assets/graphics/logos/scss.svg
    - assets/graphics/logos/supabase.svg
    - assets/graphics/logos/swift.svg
    - assets/graphics/logos/toml.svg
    - assets/graphics/logos/typescript.svg
    - assets/graphics/logos/vala.svg
    - assets/graphics/logos/xml.svg
    - assets/graphics/logos/html.svg
    - assets/graphics/logos/yaml.svg
    # Animations
    - assets/graphics/animations/gpu.riv
    - assets/graphics/animations/human.riv
  fonts:
    - family: ValeraRound
      fonts:
        - asset: assets/fonts/VarelaRound/VarelaRound-Regular.ttf
          style: normal
    - family: Neuton
      fonts:
        - asset: assets/fonts/Neuton/Neuton-Regular.ttf
          style: normal
        - asset: assets/fonts/Neuton/Neuton-Italic.ttf
          style: italic
        - asset: assets/fonts/Neuton/Neuton-Light.ttf
          weight: 300
        - asset: assets/fonts/Neuton/Neuton-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Neuton/Neuton-Bold.ttf
          weight: 700
        - asset: assets/fonts/Neuton/Neuton-ExtraBold.ttf
          weight: 800
    - family: Agave
      fonts:
        - asset: assets/fonts/Agave/AgaveNerdFontMono-Regular.ttf
          style: normal
        - asset: assets/fonts/Agave/AgaveNerdFontMono-Bold.ttf
          weight: 400
  uses-material-design: true
